### ISSUE TITLE
'Constructed question' is not constructed properly when retrieving questions in an 'exam' from file 'getAvailableExam.php'.

### ISSUE THREAD

**Issue by TheMightyE** [TheMightyE/CS490-Project#13]
**Here is a sample 'constructed' question that front receives right now:**
Write a function named "cube" that takes parameter <int num>,  and returns .

**What i really should be:**
Write a function named "cube" that takes parameter <int num>, **_take third power of input and returns the result of performing cubing operation._**

**Comment by shahhaard47** [comment]
Works fine now. @TheMightyE please reopen if you encounter problem with it again.
