### ISSUE TITLE
[Instructor Grading] Show total points next to points received.

### ISSUE THREAD

**Issue by TheMightyE** [TheMightyE/CS490-Project#19]
Show how many points each question is worth next to the points received when **instructor is grading** an exam.

![image](https://user-images.githubusercontent.com/18034577/48458635-30d1cf80-e795-11e8-8fcf-647709ed214d.png)

**Comment by TheMightyE** [comment]
Student should also be able to see the total points of a question too.

**Comment by debsanto** [comment]
The points that each question is worth is now being returned in both allStudentExamInfo and allExamsToBeGraded. Also, all data is currently being returned in raw. There is no longer a key named exam, only raw.
