### ISSUE TITLE
Questions don't keep original order when instructor is grading.

### ISSUE THREAD

**Issue by TheMightyE** [TheMightyE/CS490-Project#24]
When the instructor is grading an exam, the question numbers are not consistent when they save the exam. This bug appears to showing when the instructor adds comments to a question. The questions with the comments appear on top each time.

**Comment by debsanto** [comment]
I have edited the allExamsToBeGraded file on my end so that it returns all questions in the same order every time.

**Comment by TheMightyE** [comment]
Seems to be working, but lets not close this yet. We'll test this more as we move on.

**Comment by debsanto** [comment]
I have also modified allStudentExamInfo.php to return the questions back in the correct order every time.

**Comment by TheMightyE** [comment]
Seems to be working.
