### ISSUE TITLE
Use PHP Sessions or JS Cookies.

### ISSUE THREAD

**Issue by TheMightyE** [TheMightyE/CS490-Project#26]
Use **PHP Sessions** or **JS Cookies** to **restrict** access to pages that require a **Login**.

**Comment by TheMightyE** [comment]
I think we should use **PHP Sessions**. I read a little about them on **w3 schools** and they seem very simple. We can have **session variables** for the username, and if the session variable doesn't exist, we know the user never signed in. Very simple for now, but I think it will work. And we can make the session expire after a certain amount of time.

**Comment by shahhaard47** [comment]
Lets do it

**Comment by shahhaard47** [comment]
NOT DOING THIS
